"use strict";
exports.__esModule = true;
exports.AUCTION_TIME_LEFT = void 0;
var AUCTION_TIME_LEFT;
(function (AUCTION_TIME_LEFT) {
    AUCTION_TIME_LEFT[AUCTION_TIME_LEFT["SHORT"] = 0] = "SHORT";
    AUCTION_TIME_LEFT[AUCTION_TIME_LEFT["MEDIUM"] = 1] = "MEDIUM";
    AUCTION_TIME_LEFT[AUCTION_TIME_LEFT["LONG"] = 2] = "LONG";
    AUCTION_TIME_LEFT[AUCTION_TIME_LEFT["VERY_LONG"] = 3] = "VERY_LONG";
})(AUCTION_TIME_LEFT = exports.AUCTION_TIME_LEFT || (exports.AUCTION_TIME_LEFT = {}));
